### PR TITLE
JACOBIN-498 cli.go, cli_test.go, option_table_loader.go

### PR DESCRIPTION
**Pull request by texadactyl**
cli.go - make sure that handle_cli diagnoses all erorrs and returns them to caller.
cli_test.go - remove log level stuff and add 2 tests for -trace.
option_table_loader.go - remove verbose and update trace option handling.

and lots of other miscellaneous changes

### CODE REVIEW

**Comment by texadactyl** [comment]
Somehow, it passed on my laptop. I'll clear the cache and recompile everything.

**Comment by platypusguy** [comment]
Let's merge this when these tests pass.

**Comment by texadactyl** [comment]
Getting the unit tests to pass is a challenge.

**Comment by platypusguy** [comment]
How can I help?

**Comment by texadactyl** [comment]
Any way to get the unit tests to stop looking at log output? That is a lot of work.

**Comment by texadactyl** [comment]
3 unit tests fail:
--- FAIL: TestInsertValid (0.00s)
--- FAIL: TestInvalidLookupOfMethod_Test0 (0.00s)
--- FAIL: TestInsertionIntoMethodArea (0.00s)

**Comment by texadactyl** [comment]
**The Saga of the Closed Loop**

* The closed loop only occurred only when running in batch i.e. `go test`.
* It did not occur when running or debugging in Goland.
* It went away when I made the changes that you and I discussed last night:
     1. Do not write to stdout when stderr goes south. Instead, shutdown inside the minimalAbort clone which creates an "error" return in "test" mode (really?).
     2. Deleted failing unit test cases.

Oiy vey!

**Comment by texadactyl** [comment]
Success, finally!

As I transition log to trace, there will undoubtedly be new unit test failures. But, this is a useful baseline.

**Comment by texadactyl** [comment]
Note the CLI for trace.

```
Usage: jacobin [options] <mainclass> [args...]
	        (to execute a class)
   or jacobin [options] -jar <jarfile> [args...]
	        (to execute a jar file)
Arguments following the main class, source file, -jar <jarfile>,
are passed as the arguments to main class.

where options include:
	-client       to select the "client" VM
	-? -h -help   print this help message to the error stream
	--help        print this help message to the output stream
	-version      print product version to the error stream and exit
	--version     print product version to the output stream and exit
	-showversion  print product version to the error stream and continue
	--show-version
				  print product version to the output stream and continue

Jacobin-specific options:
	-strictJDK          make user messages conform closely to the JDK's format
	-trace=selections   display selected tracing to the console
                        where the selections are one or more of the following:
                        * init - process initilization
                        * cloadi - classloader initialization
                        * inst - bytecode interpreter trace
                        * class - class & method support for the interpreter
                        * verbose - inst, class, and more details of the interpreter
```

**Pull request merged**
