### PR TITLE
Double operations

### PR DESCRIPTION
**Pull request by suresk**

### CODE REVIEW

**Comment by texadactyl** [comment]
jacobin -trace -jar specrel.jar
```
[  0.189s] class: specrel/CommandLine, meth: main, pc: 0, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 3, inst: DSTORE_1, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 4, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 7, inst: DSTORE_3, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 8, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 11, inst: DSTORE, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 13, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 16, inst: DSTORE, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 18, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 21, inst: DSTORE, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 23, inst: LDC2_W, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 26, inst: DSTORE, tos: 1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 28, inst: GETSTATIC, tos: -1
[  0.189s] class: specrel/CommandLine, meth: main, pc: 31, inst: DLOAD, tos: 0
[  0.189s] class: specrel/CommandLine, meth: main, pc: 33, inst: INVOKESTATIC, tos: 2
[  0.189s] class: java/lang/String, meth: valueOf, pc: 0, inst: DLOAD_0, tos: -1
[  0.189s] class: java/lang/String, meth: valueOf, pc: 1, inst: INVOKESTATIC, tos: 1
[  0.189s] class: java/lang/Double, meth: toString, pc: 0, inst: DLOAD_0, tos: -1
[  0.189s] class: java/lang/Double, meth: toString, pc: 1, inst: INVOKESTATIC, tos: 1
Could not find class: jdk/internal/math/FloatingDecimal
```

**Comment by texadactyl** [comment]
Added a trace before calling classloader.FetchMethodAndCP in run.go / INVOKESTATIC.

```
		    if MainThread.Trace {
			    _ = log.Log("Calling classloader.FetchMethodAndCP with className: "+className+
				    ", methodName: "+methodName+
				    ", methodType: "+methodType,
				    log.TRACE_INST)
		    }
    		   mtEntry, err := classloader.FetchMethodAndCP(className, methodName, methodType)

```

jacobin -trace -jar specrel.jar
[  0.183s] class: specrel/CommandLine, meth: main, pc: 0, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 3, inst: DSTORE_1, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 4, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 7, inst: DSTORE_3, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 8, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 11, inst: DSTORE, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 13, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 16, inst: DSTORE, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 18, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 21, inst: DSTORE, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 23, inst: LDC2_W, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 26, inst: DSTORE, tos: 1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 28, inst: GETSTATIC, tos: -1
[  0.183s] class: specrel/CommandLine, meth: main, pc: 31, inst: DLOAD, tos: 0
[  0.183s] class: specrel/CommandLine, meth: main, pc: 33, inst: INVOKESTATIC, tos: 2
[  0.183s] Calling classloader.FetchMethodAndCP with className: java/lang/String, methodName: valueOf, methodType: (D)Ljava/lang/String;
[  0.183s] class: java/lang/String, meth: valueOf, pc: 0, inst: DLOAD_0, tos: -1
[  0.183s] class: java/lang/String, meth: valueOf, pc: 1, inst: INVOKESTATIC, tos: 1
[  0.183s] Calling classloader.FetchMethodAndCP with className: java/lang/Double, methodName: toString, methodType: (D)Ljava/lang/String;
[  0.183s] class: java/lang/Double, meth: toString, pc: 0, inst: DLOAD_0, tos: -1
[  0.183s] class: java/lang/Double, meth: toString, pc: 1, inst: INVOKESTATIC, tos: 1
[  0.183s] Calling classloader.FetchMethodAndCP with className: jdk/internal/math/FloatingDecimal, methodName: toJavaFormatString, methodType: (D)Ljava/lang/String;
Could not find class: jdk/internal/math/FloatingDecimal

**Comment by texadactyl** [comment]
I think that the issue is importing Math.

Smaller program .....

```
import java.lang.Math;

public class essai
{
	public static void main(String args[])
	{
	    double x;
	    System.out.println("===== Begin");
            x = Math.sqrt (1.0);
	    System.out.println("===== End");
        }
}
```

Execute with jacobin:
```
[  0.185s] class: essai, meth: main, pc: 0, inst: GETSTATIC, tos: -1
[  0.185s] class: essai, meth: main, pc: 3, inst: LDC, tos: 0
[  0.185s] class: essai, meth: main, pc: 5, inst: INVOKEVIRTUAL, tos: 1
===== Begin
[  0.185s] class: essai, meth: main, pc: 8, inst: DCONST_1, tos: -1
[  0.185s] class: essai, meth: main, pc: 9, inst: INVOKESTATIC, tos: 1
[  0.185s] Calling classloader.FetchMethodAndCP with className: java/lang/Math, methodName: sqrt, methodType: (D)D
[  0.185s] class: java/lang/Math, meth: sqrt, pc: 0, inst: DLOAD_0, tos: -1
[  0.185s] class: java/lang/Math, meth: sqrt, pc: 1, inst: INVOKESTATIC, tos: 1
[  0.185s] Calling classloader.FetchMethodAndCP with className: java/lang/StrictMath, methodName: sqrt, methodType: (D)D
Could not find class: java/lang/StrictMath
```

**Comment by texadactyl** [comment]
@suresk @platypusguy 
Happy Occidental New Year!

**Comment by suresk** [comment]
What does $JAVA_HOME point to? It is odd that it can't find those classes, as they should be part of the base module.

For me -

> $ jmod list $JAVA_HOME/jmods/java.base.jmod | grep Strict

```
classes/java/lang/StrictMath$RandomNumberGeneratorHolder.class
classes/java/lang/StrictMath.class
```

Although, it quickly fails after that for me - that method chain eventually ends up calling a native method, which I've started the process of figuring out how to implement.

**Comment by texadactyl** [comment]
I run all of the regression tests successfully.

jmod list $JAVA_HOME/jmods/java.base.jmod | grep Strict
```
classes/java/lang/StrictMath$RandomNumberGeneratorHolder.class
classes/java/lang/StrictMath.class
```

**Comment by texadactyl** [comment]
Math classes look correct to me .....

jmod list $JAVA_HOME/jmods/java.base.jmod | grep Math
```
classes/java/lang/Math$RandomNumberGeneratorHolder.class
classes/java/lang/Math.class
classes/java/lang/StrictMath$RandomNumberGeneratorHolder.class
classes/java/lang/StrictMath.class
classes/java/math/MathContext.class
```

**Comment by suresk** [comment]
Well, that's odd.. Could you attach your jacobin executable for me to look at?

**Comment by texadactyl** [comment]
[jacobin.zip](https://github.com/platypusguy/jacobin/files/10326570/jacobin.zip)

**Comment by suresk** [comment]
It looks like this is me misunderstanding some parts of the JMOD format. I don't think we should be filtering classes based on the manifest, as it appears that is only used for CDS purposes. I'll create another branch/ticket to fix that.

**Review by platypusguy — APPROVED** [review]
Lovely code. Enjoyed the clever use of fallthrough!

**Comment by texadactyl** [comment]
@suresk 
Opened issue #19

**Pull request merged**
