### PR TITLE
Fix JACOBIN-353

### PR DESCRIPTION
**Pull request by texadactyl**
If FetchMethodAndCP cannot find the requested methName, it causes a shutdown instead of returning a nonnil error.

runInitializationBlock is calling FetchMethodAndCP(<clinit>) in a loop, once for each superclass.

So, the first one missing a <clinit> method causes process termination.

Proposed fix: 
```
	msg := "FetchMethodAndCP: Found class " + className + ", but it did not contain method: " + methName
	return MTentry{}, errors.New(msg)
```

### CODE REVIEW

**Comment by texadactyl** [comment]
@platypusguy 

cc: @eltociear

This PR also fixes PR #68 which can now be simply closed.

**Review by platypusguy — APPROVED** [review]
Thanks for this!

**Comment by texadactyl** [comment]
@platypusguy 
Ready to merge

**Review by platypusguy — APPROVED** [review]

**Comment by texadactyl** [comment]
Needs to be merged

**Pull request merged**
