### PR TITLE
JACOBIN-582 misc updates 

### PR DESCRIPTION
**Pull request by texadactyl**
* Indicate Windows only (`//go:build windows`) in nativesExperimental_windows_test.go.
* Supplied a technote on using purego (purego.APIs.md).
* javaBaseShare-natives-byParam.md : Miscellaneous fixes, reorg to combine method types
* Established the "notes" directory for the above 2 MD files.

### CODE REVIEW

**Comment by texadactyl** [comment]
Grepping only the `###` lines (the future templates) from javaBaseShare-natives-byParam.md, I get a count of 139 templates.

**Comment by texadactyl** [comment]
The Windows sub-job is taking wayyyyyyyyyyyyyyyyyyyyyyyyyyy too long to complete.

**Review by platypusguy — COMMENTED** [review]
This should not be necessary. The _windows_ in the file name indicates the tests are for Windows only. See https://go.dev/src/os/path_windows_test.go 

Are you seeing evidence that this file is being built on non-Windows systems?

**Review by platypusguy — COMMENTED** [review]
Let's discuss tomorrow. I'm not sure this documentation should be in the code base. Perhaps in the wiki?

**Comment by texadactyl** [comment]
The Windows fail:

```
2024-09-14T21:36:25.2112151Z === RUN   TestExports
2024-09-14T21:36:25.2113548Z 2024/09/14 21:26:25 Warning: SizeOfHeaders is smaller than AddressOfEntryPoint: this file cannot run under Windows 8
2024-09-14T21:36:25.2116662Z 2024/09/14 21:26:25 AddressOfEntryPoint lies outside the sections' boundaries, AddressOfEntryPoint: 0x0
2024-09-14T21:36:25.2119468Z 2024/09/14 21:26:25 Warning: SizeOfHeaders is smaller than AddressOfEntryPoint: this file cannot run under Windows 8
2024-09-14T21:36:25.2121568Z 2024/09/14 21:26:25 AddressOfEntryPoint lies outside the sections' boundaries, AddressOfEntryPoint: 0x0
2024-09-14T21:36:25.2124320Z 2024/09/14 21:26:25 Warning: SizeOfHeaders is smaller than AddressOfEntryPoint: this file cannot run under Windows 8
2024-09-14T21:36:25.2126375Z 2024/09/14 21:26:25 AddressOfEntryPoint lies outside the sections' boundaries, AddressOfEntryPoint: 0x0
2024-09-14T21:36:25.2128268Z 2024/09/14 21:26:25 Warning: SizeOfHeaders is smaller than AddressOfEntryPoint: this file cannot run under Windows 8
2024-09-14T21:36:25.2131269Z 2024/09/14 21:26:25 AddressOfEntryPoint lies outside the sections' boundaries, AddressOfEntryPoint: 0x0
2024-09-14T21:36:25.2132535Z panic: test timed out after 10m0s
2024-09-14T21:36:25.2133181Z running tests:
2024-09-14T21:36:25.2133699Z 	TestExports (10m0s)
2024-09-14T21:36:25.2134026Z 
2024-09-14T21:36:25.2135083Z goroutine 7 [running]:
2024-09-14T21:36:25.2135734Z testing.(*M).startAlarm.func1()
2024-09-14T21:36:25.2136803Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:2259 +0x3b9
2024-09-14T21:36:25.2137792Z created by time.goFunc
2024-09-14T21:36:25.2138673Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/time/sleep.go:176 +0x2d
2024-09-14T21:36:25.2139365Z 
2024-09-14T21:36:25.2139590Z goroutine 1 [chan receive]:
2024-09-14T21:36:25.2141322Z testing.(*T).Run(0xc0000da000, {0xfc40d0?, 0xeafe8d?}, 0xfd6a10)
2024-09-14T21:36:25.2142587Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1649 +0x3c8
2024-09-14T21:36:25.2143638Z testing.runTests.func1(0x10fd4e0?)
2024-09-14T21:36:25.2144677Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:2054 +0x3e
2024-09-14T21:36:25.2145720Z testing.tRunner(0xc0000da000, 0xc000077c48)
2024-09-14T21:36:25.2147560Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1595 +0xff
2024-09-14T21:36:25.2148953Z testing.runTests(0xc00005a640?, {0x10e86d0, 0x1, 0x1}, {0xe5391f?, 0xc000077d08?, 0x10fcb20?})
2024-09-14T21:36:25.2150395Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:2052 +0x445
2024-09-14T21:36:25.2151397Z testing.(*M).Run(0xc00005a640)
2024-09-14T21:36:25.2153242Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1925 +0x636
2024-09-14T21:36:25.2154168Z main.main()
2024-09-14T21:36:25.2154834Z 	_testmain.go:47 +0x19c
2024-09-14T21:36:25.2155183Z 
2024-09-14T21:36:25.2155421Z goroutine 6 [syscall, locked to thread]:
2024-09-14T21:36:25.2156528Z syscall.SyscallN(0xc00001e980?, {0xc0000e98d0?, 0xef050a?, 0xc00002df50?})
2024-09-14T21:36:25.2158738Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/runtime/syscall_windows.go:544 +0x107
2024-09-14T21:36:25.2160382Z syscall.Syscall6(0x0?, 0xc000029ad0?, 0xc000144280?, 0xc0000e9960?, 0xef1019?, 0x25bf0ae115c?, 0xc00001bc00?, 0x69?)
2024-09-14T21:36:25.2162405Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/runtime/syscall_windows.go:488 +0x4a
2024-09-14T21:36:25.2164772Z syscall.writeFile(0xc0000e99a8?, {0xc000144280?, 0x6a, 0x80000000000?}, 0x7ffff80000000000?, 0x4?)
2024-09-14T21:36:25.2166362Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/syscall/zsyscall_windows.go:1166 +0x8e
2024-09-14T21:36:25.2167459Z syscall.WriteFile(...)
2024-09-14T21:36:25.2168402Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/syscall/syscall_windows.go:458
2024-09-14T21:36:25.2170551Z syscall.Write(0xc000061400?, {0xc000144280?, 0xc000009290?, 0x25b00000073?})
2024-09-14T21:36:25.2171920Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/syscall/syscall_windows.go:430 +0x29
2024-09-14T21:36:25.2173241Z internal/poll.(*FD).Write(0xc000061400, {0xc000144280, 0x6a, 0xa0})
2024-09-14T21:36:25.2174580Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/internal/poll/fd_windows.go:676 +0x274
2024-09-14T21:36:25.2176441Z os.(*File).write(...)
2024-09-14T21:36:25.2177305Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/os/file_posix.go:46
2024-09-14T21:36:25.2178432Z os.(*File).Write(0xc000048530, {0xc000144280?, 0x6a, 0xc0000e9b10?})
2024-09-14T21:36:25.2179595Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/os/file.go:183 +0x51
2024-09-14T21:36:25.2181577Z fmt.Fprintln({0x1000f00, 0xc000048530}, {0xc0000e9bb0, 0x1, 0x1})
2024-09-14T21:36:25.2182776Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/fmt/print.go:305 +0x6f
2024-09-14T21:36:25.2183699Z fmt.Println(...)
2024-09-14T21:36:25.2184498Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/fmt/print.go:314
2024-09-14T21:36:25.2185485Z jacobin/native.CreateNativeFunctionTable({0x0, 0x0})
2024-09-14T21:36:25.2187477Z 	D:/a/jacobin/jacobin/src/native/nativesTable_windows.go:90 +0x357
2024-09-14T21:36:25.2188494Z jacobin/native.TestExports(0xc0000da1a0)
2024-09-14T21:36:25.2189682Z 	D:/a/jacobin/jacobin/src/native/nativesExperimental_windows_test.go:34 +0x10d
2024-09-14T21:36:25.2190814Z testing.tRunner(0xc0000da1a0, 0xfd6a10)
2024-09-14T21:36:25.2191923Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1595 +0xff
2024-09-14T21:36:25.2193797Z created by testing.(*T).Run in goroutine 1
2024-09-14T21:36:25.2194961Z 	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1648 +0x3ad
2024-09-14T21:36:25.2195967Z FAIL	jacobin/native	600.052s

```

**Comment by texadactyl** [comment]
@platypusguy 
Look Ma, no Windows test 10-minute run!
Anomaly in Github Actions yesterday?
Much better.

**Pull request merged**
