### PR TITLE
JACOBIN-518 fix caught G exceptions in run.go runFrame

### PR DESCRIPTION
**Pull request by texadactyl**
Modified: run.go - Fix error handling in runFrame after calling runGframe.

### CODE REVIEW

**Review by platypusguy — COMMENTED** [review]
@texadactyl see my email. Thanks!

**Comment by texadactyl** [comment]
@platypusguy Please see my email reply. Thanks!

**Comment by texadactyl** [comment]
jacotest v3.2.13 W-L = 79-55 (.587).
Hope to improve that with BigInteger functions (in-flight).

**Comment by texadactyl** [comment]
Sorry, some of the pushes had no JACOBIN-xxx prefix. They were minor stuff that I saw while investigating other matters.

**Comment by texadactyl** [comment]
jacotest v3.2.14 W-L = 81-54 (.600).

**Pull request merged**
