### PR TITLE
Trap user-specified Charset in String.getBytes(...)

### PR DESCRIPTION
**Pull request by texadactyl**
This covers the cases:
* getBytes(string)
* getBytes(Charset)

### CODE REVIEW

**Comment by texadactyl** [comment]
This work was mentioned in JACOBIN-384.

**Review by platypusguy — COMMENTED** [review]
I'm OK with the handling of the charset version, but why not implement java/lang/String.getBytes(Ljava/lang/String;)[B ? That's a trivial implementation, that can be extracted directly from the code already in the present getBytes() implementation. 

LMK if I'm missing the rationale for not implementing it.

**Comment by texadactyl** [comment]
That would imply (a) implementing a Charset object and (b) supporting
translation from all possible charsets to the currently in use charset. I
suggest postponing it.

**Comment by platypusguy** [comment]
Ah, right, the passed string is not the string whose bytes are being sought, but the name of the charset. Agree with your POV. Will merge.

**Pull request merged**
