### PR TITLE
added tracing to run.go, fixed JACOBIN-252

### PR DESCRIPTION
**Pull request by texadactyl**
See https://jacobin.myjetbrains.com/youtrack/issue/JACOBIN-249

### CODE REVIEW

**Comment by platypusguy** [comment]
We should not change the size of the method's operand stack. See comments on JACOBIN-249

**Comment by texadactyl** [comment]
What about double pushes?

**Review by platypusguy — CHANGES_REQUESTED** [review]
I'm in two minds about whether additional diagnostic info should be included in -trace:inst. Let's go ahead and see whether that helps or hinders. I might ask that you print the function name in addition to the other parameters you list. It is stored in f.MethName

**Comment by texadactyl** [comment]
[  0.194s] StartExec: f.MethName=main, m.MaxStack=2, m.MaxLocals=2, len(m.Code)=82

**Comment by texadactyl** [comment]
Now, we could add source line numbers in the opcode traces

**Comment by platypusguy** [comment]
JACOBIN-247. Thank you!

**Review by platypusguy — COMMENTED** [review]
All good. Thanks!

**Pull request merged**
