### PR TITLE
fixed jvm/TestHello2Class_test.go

### PR DESCRIPTION
**Pull request by texadactyl**
JACOBIN-270

@platypusguy - In TestHello2Class_test.go,
*  I created a ```redirecting``` boolean and set it false while tracing etc. for visibility. It's now set to true so the unit test behaves the way you intended. And, it passes.
* I added loading the base classes. See late breaking news below.

In addition,
* Unfortunately, due to my inexperience with ```goland```, some significant reformatting of significant & insignificant source occurred. Oh, darn.
* I amended more code to log available evidence when something goes wrong.
* getClassBytes() --> GetClassBytes() for visibility. Also, it is passing back the error gizmo when it has trouble instead of shutdown. Pass the buck! Seriously, its an opportunity for both callee and caller to be identified in a SEVERE error message.
* Yeah, I tried to move the call to LoadBaseClasses from jvmStart.go to classloader.Init. Result: a whole buncha broken tests because they counted & compared the number of loaded classes! LOL@myself.

### CODE REVIEW

**Comment by texadactyl** [comment]
Late breaking news ................................
If one comments out the following:
```
	// Load the base classes
	global := *globals.GetGlobalRef()
	classloader.LoadBaseClasses(&global)
	t.Logf("LoadBaseClasses ok\n")
```

THEN this occurs:
```
Got error from StartExec(): GETSTATIC: could not find static field java/lang/System.out in class java/lang/System
```

**Comment by texadactyl** [comment]
Note also that loading non-bootstrap files from jmods is still suspect.

**Comment by texadactyl** [comment]
```GetClassBytes```
I did remember to suffix the class name with ".class".
Yes, I forgot to prefix the class name with "classes/".

**Comment by texadactyl** [comment]
Latest jacotest run:
```
Failed Test Case Summary - 2023-06-11 14:57:54 CDT
 
===========================
panic: interface conversion
===========================
FAILED.JACOBIN-0206-nbody.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0211-pbcrypto.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0217-multidim-3d.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0234-0240-0241-array-length.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0234-string-length.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.array-list-iterator.jacobin.log: panic: interface conversion: interface {} is nil, not int64
FAILED.arrays-1.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.blockchain.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.casting.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.catch-exception.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.dedupe-hacked.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.emission-line-spectra.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.fits.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.hashed-map.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.hashed-set.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.java17-enhancements.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.kalman-filtering.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.linked-list.jacobin.log: panic: interface conversion: interface {} is int64, not *object.Object
FAILED.scimark2.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.sha3.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.solitairgraphy.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.stringer.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.two-fish.jacobin.log: panic: interface conversion: interface {} is *[]int8, not *object.Object
FAILED.vectors.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.zippy.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
--- Total: 25
 
=================================
runtime error: index out of range
=================================
FAILED.negtest-runner-timeout.jacobin.log: panic: runtime error: index out of range [0] with length 0
FAILED.user-defined-exception.jacobin.log: panic: runtime error: index out of range [2] with length 1
--- Total: 2
 
============================
could not find or load class
============================
 
=====================================
runtime error: invalid memory address
=====================================
 
=====================================
MethAreaFetch
=====================================
 
================
runtime.sigpanic
================
 
================
invalid bytecode
================
FAILED.lambdas-maps.jacobin.log: Invalid bytecode found: 186 (0xBA)(INVOKEDYNAMIC) at location 10 in method main() of class main
--- Total: 1
```

**Comment by texadactyl** [comment]
Still, there are some class not found situations needing investigation in ```FetchMethodAndCP``` and ```instantiateClass```:

```
FAILED.elliptic.jacobin.log:FetchMethodAndCP: WaitClassStatus: Timeout waiting for class {java/security/KeyPairGenerator} status
FAILED.JACOBIN-0161-0229-classes.jacobin.log:FetchMethodAndCP: WaitClassStatus: Timeout waiting for class {Outsider} status
FAILED.JACOBIN-0231-stats.jacobin.log:Error instantiateClass: WaitClassStatus: Timeout waiting for class {Library} status
FAILED.numbers-chars-strings.jacobin.log:FetchMethodAndCP: WaitClassStatus: Timeout waiting for class {ProcCharacter} status
FAILED.packaging-1.jacobin.log:Error instantiateClass: WaitClassStatus: Timeout waiting for class {pkgcalc/Calculator} status
FAILED.sockets.jacobin.log:Error instantiateClass: WaitClassStatus: Timeout waiting for class {MyThread} status
FAILED.specrel.jacobin.log:FetchMethodAndCP: WaitClassStatus: Timeout waiting for class {Formulae} status
FAILED.taylor-series.jacobin.log:Error instantiateClass: WaitClassStatus: Timeout waiting for class {BigRational} status
FAILED.threading.jacobin.log:Error instantiateClass: WaitClassStatus: Timeout waiting for class {MyThread} status
FAILED.tls-one-way.jacobin.log:FetchMethodAndCP: WaitClassStatus: Timeout waiting for class {java/security/SecureRandom} status

```

**Comment by texadactyl** [comment]
Oddly enough, ```packaging-1``` runs successfully from the command line!

**Review by platypusguy — APPROVED** [review]
See my email about the code formatting issue.

**Comment by platypusguy** [comment]
JACOBIN-270

**Pull request merged**
