### PR TITLE
Solved StrictMath anomaly in FetchMethodAndCP

### PR DESCRIPTION
**Pull request by texadactyl**
JACOBIN-270
JACOBIN-271

It wasn't just StrictMath. It was any INVOKESTATIC situation that required loading a not previously loaded class.

FetchMethodAndCP now calls LoadClassFromNameOnly(classname) to make sure that the class is loaded if need be.

AND FetchMethodAndCP **ONLY** calls LoadClassFromNameOnly when MethAreaFetch says the class aint loaded!

### CODE REVIEW

**Comment by texadactyl** [comment]
I could only get them to fail once:  When I first re-installed jacobin. Even with cleaning the cache, recompiling, and retesting, they all pass.  The list:

```
TestRunArrlen (0.23s)
TestRunBitShifts (0.22s)
TestRunHello (0.22s)
TestRunHelloVerboseClass (0.24s)
TestRunHelloVerboseFinest (1.80s)
TestRunHelloTraceInst (0.22s)
TestRunHello2 (0.23s)
TestRunHello2VerboseClass (0.24s)
TestRunHello2VerboseFinest (1.70s)
TestRunHello2TraceInst (0.22s)
TestRunHello3 (0.22s)
TestRunHello3VerboseClass (0.23s)
TestRunHello3VerboseFinest (1.74s)
TestRunHello3TraceInst (0.22s)
TestRunNanoprint (0.22s)

jacobin/wholeClassTests	7.[960](https://github.com/platypusguy/jacobin/actions/runs/5244589994/jobs/9470817670?pr=39#step:6:961)s

```

**Comment by texadactyl** [comment]
Now, doing the same steps, I can get them to fail consistently.

**Comment by texadactyl** [comment]
Simple test case:
```
public class main {
    public static void main(String[] args) {  
		double y = 3.1;
    }
}
```
It runs fine inside directory ```essai``` where the class file resides.
Change directory to parent (..)
and then run ```jacobin -trace essai/main.class```
Here is the issue:
```
[  0.370s] LoadClassFromFile: File essai/main.class was read
[  0.370s] WaitForClassStatus: class name: main
[  0.370s] MethAreaFetch: key(main) --> not nil
[  0.370s] MethAreaFetch: key(main) --> not nil
[  0.370s] LoadClassFromNameOnly: Load class from file main
LoadClassFromFile: os.ReadFile(main.class) failed
LoadClassFromNameOnly: LoadClassFromFile main failed
open main.class: no such file or directory
LoadBaseClasses: Loading main failed: open main.class: no such file or directory
open main.class: no such file or directory
[  0.370s] MethAreaFetch: key(java/lang/Object) --> not nil
[  0.370s] MethAreaFetch: key(main) --> not nil
```

**Comment by texadactyl** [comment]
Initial comment was updated.
 FetchMethodAndCP **ONLY** calls LoadClassFromNameOnly when MethAreaFetch says the class aint loaded!

**Comment by texadactyl** [comment]
Last jacotest failure report.

- 32 interface conversion errors.
- 5 index value errors.
- 1 INVOKEDYNAMIC.

```
Failed Test Case Summary - 2023-06-12 11:14:29 CDT
 
===========================
panic: interface conversion
===========================
FAILED.JACOBIN-0206-nbody.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0211-pbcrypto.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0217-multidim-3d.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0234-0240-0241-array-length.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.JACOBIN-0234-string-length.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.array-list-iterator.jacobin.log: panic: interface conversion: interface {} is nil, not int64
FAILED.arrays-1.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.blockchain.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.casting.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.catch-exception.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.dedupe-hacked.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.elliptic.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.emission-line-spectra.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.fits.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.hashed-map.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.hashed-set.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.java17-enhancements.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.kalman-filtering.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.linked-list.jacobin.log: panic: interface conversion: interface {} is int64, not *object.Object
FAILED.numbers-chars-strings.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.scimark2.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.sha3.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.sockets.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.solitairgraphy.jacobin.log: panic: interface conversion: interface {} is int, not *object.Object
FAILED.strict-math.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.stringer.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.taylor-series.jacobin.log: panic: interface conversion: interface {} is nil, not *object.Object
FAILED.threading.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.tls-one-way.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
FAILED.two-fish.jacobin.log: panic: interface conversion: interface {} is *[]int8, not *object.Object
FAILED.vectors.jacobin.log: panic: interface conversion: interface {} is int, not int64
FAILED.zippy.jacobin.log: panic: interface conversion: interface {} is *object.Object, not int64
--- Total: 32
 
=================================
runtime error: index out of range
=================================
FAILED.JACOBIN-0161-0229-classes.jacobin.log: panic: runtime error: index out of range [1] with length 1
FAILED.JACOBIN-0231-stats.jacobin.log: panic: runtime error: index out of range [0] with length 0
FAILED.negtest-runner-timeout.jacobin.log: panic: runtime error: index out of range [0] with length 0
FAILED.specrel.jacobin.log: panic: runtime error: index out of range [0] with length 0
FAILED.user-defined-exception.jacobin.log: panic: runtime error: index out of range [2] with length 1
--- Total: 5
================
invalid bytecode
================
FAILED.lambdas-maps.jacobin.log: Invalid bytecode found: 186 (0xBA)(INVOKEDYNAMIC) at location 10 in method main() of class main
--- Total: 1
================
WaitClassStatus
================
 
============================
could not find or load class
============================
 
=====================================
runtime error: invalid memory address
=====================================
 
=====================================
MethAreaFetch
=====================================
 
================
runtime.sigpanic
================
 
```

**Review by platypusguy — APPROVED** [review]
Not sure why that caused the problem, but appreciate you getting it fixed. See my email about modifying the logging levels to better reflect need.

**Comment by texadactyl** [comment]
@platypusguy 

**Problem 1 (pre-existing)**
* StrictMath is not in the lib/classlist, hence, not loaded as a "base" class.
* Before this fix, INVOKESTATIC processing called FetchMethodAndCP for StrictMath --> class not found.
* Fix: I modified FetchMethodAndCP to use LoadClassFromNameOnly. That solved the StrictMath issue.

**Problem 2 (the original push here created this one)**
* The fix to problem 1 had a side effect.
*  JVMRun sets up the start up class with LoadClassFromFile.
* Then, it calls run.go StartExec which uses FetchMethodAndCP for the start up class. 
* But, the start up class path used to find it is no longer available, hence, the class name was used without the rightful directory prefix and not found. But, we shouldn't have tried to load the start up class a second time (makes no sense).
* Fix: FetchMethodAndCP modified again to only call LoadClassFromNameOnly when MethAreaFetch says the classisn't already loaded.

**Comment by texadactyl** [comment]
@platypusguy 

Problem 2 does not matter if the start up class is in the current working directory. We erroneously loaded the class twice but the second load worked. 

However, many of the ```wholeClassTests``` test cases and others failed when I had not applied the fix to problem 2 of the previous post.

**Comment by platypusguy** [comment]
Thanks for finding this nurdle in Problem 2. One of the things I highly recommend to people to do is to step through their program in a debugger to make sure that it's actually doing what they think, rather than doing some things twice, other things not at all (which gap is obscured by other actions), etc. Looks like I could benefit from my own advice!

**Pull request merged**
