### PR TITLE
Floating point operations

### PR DESCRIPTION
**Pull request by suresk**
- Implemented most floating point operations (array and compare ones TBD).
- Updated missing bytecode messaging
- Improved classloader resolution

### CODE REVIEW

**Review by platypusguy — APPROVED** [review]
JACOBIN-204 This looks great. Thanks!

**Comment by texadactyl** [comment]
@suresk

jacobin -version
```
Jacobin VM, Copyright © 2021-2 by the Jacobin authors. MPL 2.0 License. www.jacobin.org
Jacobin VM v. 0.2.1 (Java 17) 
64-bit server VM
source: c6332e1b6364a9eec075d719588ea0b0629d1fb8, dated 2022-12-28T01:06:36Z
```
run.sh (tinyjar)
```
++ jacobin -trace -jar specrel.jar
[  0.276s] class: specrel/CommandLine, meth: main, pc: 0, inst: LDC2_W, tos: -1
[  0.276s] class: specrel/CommandLine, meth: main, pc: 3, inst: DSTORE_1, tos: 1
Invalid bytecode found: 72 (0x48) (DSTORE_1) at location 3 in method main() of class specrel/CommandLine
```

**Comment by suresk** [comment]
@texadactyl Double operations are next on this list - hopefully within the next week or so.

**Comment by texadactyl** [comment]
@suresk  No rush.  I am not bored.  (:

**Pull request merged**
