### PR TITLE
Fix JACOBIN-231 closed loop

### PR DESCRIPTION
**Pull request by texadactyl**
This also seems to remedy some pointer errors (segmentation violation) seen in the logs.

### CODE REVIEW

**Review by platypusguy — COMMENTED** [review]
Thanks for this, Richard. It's a good temporary fix until we get more robust handling of the classpath added to Jacobin. My only preference would be a shorter period: may be 4 x 500 ms. I can make the change or you can, if you prefer. LMK and I'll pull this in. Thanks again!

**Comment by texadactyl** [comment]
4 x 500 ms sounds fine to me.

**Comment by texadactyl** [comment]
@platypusguy Made the change and PR is ready for merge.

**Comment by texadactyl** [comment]
Working on some tests for Java 17 new features and the Vectors (16?).

**Comment by texadactyl** [comment]
Jeeeeeeeesh it takes a lot of syntax to set up an initialized vector!!!

**Comment by texadactyl** [comment]
I need to look at the codecov/patch complaints. Not a big deal, just annoying.

**Comment by texadactyl** [comment]
Code coverage for golang: https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/

**Comment by texadactyl** [comment]
@platypusguy 

Jacobin is not doing code coverage according to their recommendation (see URL in a previous message of mine).  This is the pattern they recommend:
```
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
```
Also, you are supposed to register yourself as a user and jacobin as a repo.

I think that jacobin testing is meeting your needs at the moment even though the unit tests are probably missing a lot of source code at the moment.

Reaction?

**Comment by texadactyl** [comment]
Synced latest platypusguy/jacobin updates

**Comment by platypusguy** [comment]
JACOBIN-231 Merge of @texadactyl's refinement of class-loading loop.

**Comment by platypusguy** [comment]
I have moved the conversation about CodeCov to JACOBIN-245 on the YouTrack instance for further discussion.

**Pull request merged**
