### PR TITLE
JACOBIN-502 work on native functions for java/util/Random

### PR DESCRIPTION
**Pull request by texadactyl**
Exceptions:
* The stream output (E.g. IntStream) has no coverage.
* Trapped: protected int next(int bits).  Source code: "This method should never be reached unless done by reflection so we should throw when tried".

### CODE REVIEW

**Comment by texadactyl** [comment]
See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html

The following public functions are undocumented:
- public boolean isDeprecated()
- public int nextInt(int origin, int bound)
- public long nextLong(long bound) 
- public long nextLong(long origin, long bound)
- public float nextFloat(float origin, float bound)
- public double nextDouble(double origin, double bound)
- public double nextExponential()
- public String toString()

**Comment by texadactyl** [comment]
jacotest 3.2.3 W-L: 73-56 (.566)

**Comment by platypusguy** [comment]
> See https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/util/Random.html
> 
> The following public functions are undocumented:
> 
> * public boolean isDeprecated()
> * public int nextInt(int origin, int bound)
> * public long nextLong(long bound)
> * public long nextLong(long origin, long bound)
> * public float nextFloat(float origin, float bound)
> * public double nextDouble(double origin, double bound)
> * public double nextExponential()
> * public String toString()

Where are you seeing that these methods are public? I'm looking at the source code and the scope in all cases is `default`, which is `package`, not `public`. Is there some other place where they're listed as public?

**Comment by texadactyl** [comment]
@platypusguy 
See src/java.base/share/classes/java/util/Random.java
Starting at line 133.
But, I missed that they were inside 
```private static final class RandomWrapper extends Random implements RandomGenerator```, at line 93.  
Sometimes, this language defies practicality.

**Comment by texadactyl** [comment]
The following program compiles and executes with the OpenJDK JVM:
```
import java.util.Random;

public class main {
	public static void main(String[] args) {
	
		Random rr = new Random();
		System.out.println(rr.isDeprecated());
		System.out.println(rr.nextInt(0, 10));
		System.out.println(rr.nextLong(10l));
		System.out.println(rr.nextLong(0l, 10l));
		System.out.println(rr.nextFloat(0.0f, 10.0f));
		System.out.println(rr.nextDouble(0.0f, 10.0f));
		System.out.println(rr.nextExponential());
		System.out.println(rr.toString());
	
	}
}
```

The Linux copy of Random.java is attached:
[Random.java.zip](https://github.com/platypusguy/jacobin/files/15218523/Random.java.zip)

**Comment by texadactyl** [comment]
In Random.java, for example, I saw ```public boolean isDeprecated()``` at line 133.

**Comment by platypusguy** [comment]
I'm a moron. Pay no attention to my previous explanation. `default` is the keyword used in Java interfaces to show a default implementation. All interface methods are `public`, so the methods marked `default` are inherently public, which explains why the above code runs. 

I can't explain why they're not documented unless the Java team felt that because they're in an interface, which invites a separate implementation, the explanation might not match the actual operation.

**Pull request merged**
