### PR TITLE
Classloader cleanup +getting ready for the Big Bang

### PR DESCRIPTION
**Pull request by texadactyl**
@platypusguy 
This is an initial PR. You can merge it any time. If still open, I will add to it. Otherwise, I'll open a new PR.

This list will continue to be updated.
* Added shutdowns in classloader.go LoadBaseClasses error situations.
* Added and amended commentary in a few places classloader.go - some based on discussion in JACOBIN-268.
* Updated some URLs to point to the Java/JVM version 17 documentation.
* Removed reference to JacobinHome from LoadClassByNameOnly (to be extensively revamped). As it turns out, this change was not necessary at this time. Jacobin home directory concept is still under discussion.
* In LoadClassByNameOnly, logging with accompanying context was added at the points of error recognition.
* Add the name of the function in several error messages so to see explicitly which function was reporting.
* In jvm/instantiate.go instantiateClass, when a class cannot be loaded, a shutdown is called.
* Confine MethArea locking to the methArea.go source file (take it out of instantiate.go).
* JACOBIN_HOME set up in globals.go.
* Make jvmStart.go JVMRun field the potential err from classloader.Init.
* Added context to some of jmod.go comments.
* Added JAVA_HOME installation version from the release file in globals.go and globals_test.go.

### CODE REVIEW

**Comment by texadactyl** [comment]
I made a trade-off. I could have had LoadClassByNameOnly do a shutdown but that might have been disruptive in terms of return error vs no return error to caller. Since instantiateClass was the only significant caller, I decided to leave the interface as-is.

**Comment by texadactyl** [comment]
Note: Errors are no longer tolerated with warnings -- E.g.
* Missing JAVAommand line option that cannot be recognized_HOME
* Unrecognizable command line option

"This is the way"

**Review by platypusguy — COMMENTED** [review]
In InitJacobinHome() in globals.go, it appears that even if you find the JACOBIN_HOME directory, you still create it. I think the logic for around os.MkdirAll() needs to be in the else branch of the preceding if-statement. Or am I missing something?

**Review by platypusguy — COMMENTED** [review]
In instantiate.go, I see you have the RLock around the call to MethAreaFetch(). Were we not going to move the RLock to inside the MethAreaFetch()?

**Comment by texadactyl** [comment]
@platypusguy 
All lock references were removed from instantiate.go.

**Comment by texadactyl** [comment]
@platypusguy Yes, whether all the elements of a directory chain exist or not, one can call MkDirAll and all the directory branches that exist will be created and those that are already there are skipped over. Its like a create something if it isn't there but no harm no foul if it is.

**Comment by texadactyl** [comment]
@platypusguy 
I think that its time to merge this. Tomorrow, I am planning to start on the JACOBIN_HOME and jmod processing
in the jmodFinder.go file (doesn't exist - have a better name?). I'd like to start with us in sync.
If you still have issues with this PR, please call me.

**Comment by platypusguy** [comment]
JACOBIN-266 Preparation for reading accessing all jmod files when needed for execution. Thanks @texadactyl for this!

**Pull request merged**
