### PR TITLE
JACOBIN-476 trap SecurityManager, enable java/lang/arraycopy

### PR DESCRIPTION
**Pull request by texadactyl**
* The SecurityManager is deprecated so trapping it as such.

* Added MethodSignatures entry for arraycopy to ```javaLangSystem.go```:
```
	MethodSignatures["java/lang/System.arraycopy.(Ljava/lang/Object;ILjava/lang/Object;II)V"] =
		GMeth{
			ParamSlots: 5,
			GFunction:  arrayCopy,
		}

```

### CODE REVIEW

**Comment by texadactyl** [comment]
For some reason which I cannot see, the J function is being attempted and diagnosed as "native" even though the G function arrayCopy is being loaded into MTable. ???

Small test:
```
public class main {
    public static void main(String[] args) {
		int input[] = new int[32];
		for (int ii = 0; ii < 32; ii++)
			input[ii] = ii;
		int output[] = new int[32];
		System.arraycopy(output, 0, input, 0, 32);
    }
}
```

How did I screw up?

**Comment by platypusguy** [comment]
See my email. The problem is that your signature contains a spurious dot. See if my recent commit solves the problem and LMK. Thanks!

**Comment by texadactyl** [comment]
The "minor fixes" include the following:
* run.go - Take the spurious dot (.) out of the INVOKESTATIC complaint messages.
* javaLangSystem.go - fix signature - "java/lang/System.arrayCopy" --> "java/lang/System.arraycopy".

**Comment by texadactyl** [comment]
The small test passes.

**Comment by texadactyl** [comment]
jacotest 3.1.13 W-L 71-55 (.563) - almost as good as the Mutts!

**Comment by texadactyl** [comment]
Note:
```
10:02:28 Looking for test cases with changed results .....
	cur  >>  blockchain  jacobin   2024-04-22  15:02:28.447  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8()Z
	prv  >>  blockchain  jacobin   2024-04-21  22:03:46.632  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8.()Z
	cur  >>  desi  jacobin   2024-04-22  15:02:28.409  failed  ARRAYLENGTH: Invalid (null) value for *object.Object
	prv  >>  desi  jacobin   2024-04-21  22:03:46.634  failed  INVOKESTATIC: Native method requested: java/lang/System.arraycopy.(Ljava/lang/Object;ILjava/lang/Object;II)V
	cur  >>  elliptic  jacobin   2024-04-22  15:02:28.449  failed  INVOKEVIRTUAL: Native method requested: jdk/internal/misc/Unsafe.getIntVolatile(Ljava/lang/Object;J)I
	prv  >>  elliptic  jacobin   2024-04-21  22:03:46.636  failed  INVOKEVIRTUAL: Native method requested: jdk/internal/misc/Unsafe.getIntVolatile.(Ljava/lang/Object;J)I
	cur  >>  fits  jacobin   2024-04-22  15:02:28.451  failed  INVOKESTATIC: Native method requested: java/io/RandomAccessFile.initIDs()V
	prv  >>  fits  jacobin   2024-04-21  22:03:46.638  failed  INVOKESTATIC: Native method requested: java/io/RandomAccessFile.initIDs.()V
	cur  >>  imageio-output  jacobin   2024-04-22  15:02:28.453  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8()Z
	prv  >>  imageio-output  jacobin   2024-04-21  22:03:46.640  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8.()Z
	cur  >>  java-logging  jacobin   2024-04-22  15:02:28.454  failed  INVOKEVIRTUAL: Native method requested: java/lang/Class.initClassName()Ljava/lang/String;
	prv  >>  java-logging  jacobin   2024-04-21  22:03:46.641  failed  INVOKEVIRTUAL: Native method requested: java/lang/Class.initClassName.()Ljava/lang/String;
	cur  >>  jframe-1  jacobin   2024-04-22  15:02:28.456  failed  INVOKESTATIC: Native method requested: java/security/AccessController.getStackAccessControlContext()Ljava/security/AccessControlContext;
	prv  >>  jframe-1  jacobin   2024-04-21  22:03:46.644  failed  INVOKESTATIC: Native method requested: java/security/AccessController.getStackAccessControlContext.()Ljava/security/AccessControlContext;
	cur  >>  rsa-mini  jacobin   2024-04-22  15:02:28.459  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8()Z
	prv  >>  rsa-mini  jacobin   2024-04-21  22:03:46.646  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8.()Z
	cur  >>  scimark2  jacobin   2024-04-22  15:02:28.417  failed  AASTORE: Attempt to access array of incorrect type
	prv  >>  scimark2  jacobin   2024-04-21  22:03:46.648  failed  INVOKESTATIC: Native method requested: java/lang/System.arraycopy.(Ljava/lang/Object;ILjava/lang/Object;II)V
	cur  >>  stack-walk  jacobin   2024-04-22  15:02:28.460  failed  INVOKESTATIC: Native method requested: java/lang/Thread.currentThread()Ljava/lang/Thread;
	prv  >>  stack-walk  jacobin   2024-04-21  22:03:46.650  failed  INVOKESTATIC: Native method requested: java/lang/Thread.currentThread.()Ljava/lang/Thread;
	cur  >>  threading  jacobin   2024-04-22  15:02:28.442  failed  error: go panic because of interface conversion: interface {} is []uint8, not *object.Object
	prv  >>  threading  jacobin   2024-04-21  22:03:46.652  failed  INVOKESTATIC: Native method requested: java/lang/System.arraycopy.(Ljava/lang/Object;ILjava/lang/Object;II)V
	cur  >>  tls-one-way  jacobin   2024-04-22  15:02:28.462  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8()Z
	prv  >>  tls-one-way  jacobin   2024-04-21  22:03:46.654  failed  INVOKESTATIC: Native method requested: java/util/concurrent/atomic/AtomicLong.VMSupportsCS8.()Z
10:02:28 Number of test cases with changed results = 12
```

As you can see,
* Some test cases moved on to other exciting things.
* Some just had their error message corrected to get rid of the erroneous period (.). Good!
* One that moved on failed to display the evidence at hand: "scimark2  jacobin   2024-04-22  15:02:28.417  failed  AASTORE: Attempt to access array of incorrect type". I'll look into this shortly.

**Comment by texadactyl** [comment]
I think we need a cleanup of error logging:
* General strategy is not clear to me.
* Even with removal of redundant logging we still see complaints twice.

**Comment by texadactyl** [comment]
Removed last commit because it is pain to fix tests that need precise wording in error messages.
We need a general cleanup of error logging.
- General strategy is not clear to me.
- Even with removal of redundant logging we still see complaints twice.

**Pull request merged**
